---
title: "A simple example of how to use voluModel for niche modeling"
author:
- Hannah L. Owens
- Carsten Rahbek
date: "`r Sys.Date()`"
output:
  rmarkdown::html_vignette:
    fig_caption: yes
    toc: true
    toc_depth: 3
vignette: >
  %\VignetteIndexEntry{A simple example of how to use voluModel for niche modeling}
  \usepackage[utf8]{inputenc}
  %\VignetteEncoding{UTF-8}
  %\VignetteEngine{knitr::rmarkdown}
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, error = TRUE)
knitr::opts_knit$set(root.dir = system.file('extdata/', package='occCite'))
```

# Introduction 
Coming soon. Stay tuned.

# Data Inputs

```{r environmental data, eval=FALSE}

```

```{r environmental data processing, eval=FALSE}

```

```{r occurrence data, eval=FALSE}

```

# Background Sampling

```{r automatic sampling region generation, eval=FALSE}

```

```{r environmental background sampling, eval=FALSE}

```

# Niche model generation

```{r generate niche model, eval=FALSE}

```

# Niche model generation

```{r project niche model, eval=FALSE}

```

```{r visualize niche model, eval=FALSE}

```

# Bonus feature: Diversity map generation

```{r stack presence/absence rasters, eval=FALSE}

```

```{r plot diversity map, eval=FALSE}

```
